### ISSUE TITLE
Export of DiscretizedMoveItIKSolver

### ISSUE THREAD

**Issue by collinthornton** [ros-industrial/reach_ros2#31]
The export of the `DiscretizedMoveItIKSolver` has a typo. See:

https://github.com/ros-industrial/reach_ros2/blob/5cc3b4fb1bcbe90984c23877b5688e84a525672f/src/plugins.cpp#L16

The code is currently:
```
EXPORT_IK_SOLVER_PLUGIN(reach_ros::ik::DiscretizedMoveItIKSolverFactory, DiscretizedMoveItIKSolverFactory)
```

and should be:
```
EXPORT_IK_SOLVER_PLUGIN(reach_ros::ik::DiscretizedMoveItIKSolverFactory, DiscretizedMoveItIKSolver)
```

**Comment by marip8** [comment]
Closing; addressed in #32
